#ifndef SHELLEXT_OVERLAY_GLOBAL_H
#define SHELLEXT_OVERLAY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHELLEXT_OVERLAY_LIBRARY)
#  define SHELLEXT_OVERLAYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHELLEXT_OVERLAYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHELLEXT_OVERLAY_GLOBAL_H
